In [12]:
import torch
from gensn.variational import VariationalBound
import gensn.distributions as G
import torch.distributions as D
from torch import nn
from gensn.parameters import TransformedParameter
from gensn.variational import VariationalBound
from torch.optim import Adam

In [9]:
prior = G.TrainableDistributionAdapter(
    D.Normal, loc=nn.Parameter(torch.Tensor([0.0])), scale=torch.Tensor([2.0])
)
conditional = G.TrainableDistributionAdapter(
    D.Normal,
    loc=nn.Linear(1, 1),
    scale=TransformedParameter(torch.Tensor([1.0]), torch.abs),
)
joint = G.Joint(prior=prior, conditional=conditional)
posterior = G.TrainableDistributionAdapter(
    D.Normal, loc=nn.Parameter(torch.Tensor([0.0])), scale=torch.Tensor([2.0])
)

In [11]:
model = VariationalBound(joint=joint, posterior=posterior)

In [13]:
optimizer = Adam(model.parameters(), lr=0.01)

In [16]:
list(model.parameters())

[Parameter containing:
 tensor([0.], requires_grad=True),
 Parameter containing:
 tensor([[-0.7081]], requires_grad=True),
 Parameter containing:
 tensor([-0.1306], requires_grad=True),
 Parameter containing:
 tensor([1.], requires_grad=True),
 Parameter containing:
 tensor([0.], requires_grad=True)]

In [17]:
optimizer.param_groups[0]["params"]

[Parameter containing:
 tensor([0.], requires_grad=True),
 Parameter containing:
 tensor([[-0.7081]], requires_grad=True),
 Parameter containing:
 tensor([-0.1306], requires_grad=True),
 Parameter containing:
 tensor([1.], requires_grad=True),
 Parameter containing:
 tensor([0.], requires_grad=True)]